version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-network

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - kafka-network

  mqtt-kafka-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-kafka-bridge
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mqtt
    networks:
      - kafka-network

networks:
  kafka-network:
